//! # Banco de Dados em Memória para Desenvolvimento Mock-First
//!
//! Fornece armazenamento persistente em runtime WebAssembly para testes de UI
//! sem necessidade imediata do backend ativo.

use shared::documents::{ContractTemplate, PatientDocument};

use shared::anamnesis::AnamnesisResponseItem;
use shared::appointments::{
    AgendaResourceOption, AgendaResourcesResponse, AppointmentResponse,
    AppointmentStatus, AppointmentType, AssignedUserDto, ConsumedItemDto,
};
use shared::clinics::{ClinicAddress, ClinicResponse};
use shared::finance::{
    Transaction, TransactionDirection, TransactionPaymentEntry, TransactionStatus,
};
use shared::patients::{
    Patient, PatientAnamnesis, PatientExam, PatientTreatment,
};
use shared::stock::{
    EquipmentStatus, InventoryItem, ItemType, StockMovement,
};
use shared::treatments::{
    PatientTreatmentPlan, TreatmentTemplate,
};
use shared::users::UserResponse;
use std::sync::{LazyLock, Mutex};

pub struct MockDatabase {
    pub patients: Vec<Patient>,
    pub anamneses: Vec<PatientAnamnesis>,
    pub exams: Vec<PatientExam>,
    pub patient_treatments: Vec<PatientTreatment>,
    pub appointments: Vec<AppointmentResponse>,
    pub transactions: Vec<Transaction>,
    pub inventory_items: Vec<InventoryItem>,
    pub stock_movements: Vec<StockMovement>,
    pub treatment_templates: Vec<TreatmentTemplate>,
    pub treatment_plans: Vec<PatientTreatmentPlan>,
    pub contract_templates: Vec<ContractTemplate>,
    pub patient_documents: Vec<PatientDocument>,
    pub users: Vec<UserResponse>,
    pub clinics: Vec<ClinicResponse>,
    /// Mapa username -> senha em texto plano (apenas para mock de desenvolvimento)
    pub password_map: std::collections::HashMap<String, String>,
}

pub static DB: LazyLock<Mutex<MockDatabase>> = LazyLock::new(|| Mutex::new(init_mock_database()));

fn init_mock_database() -> MockDatabase {
    let patients = vec![
        Patient {
            id: "patient:maria_barbosa".to_string(),
            clinic_id: "clinic:smile_plus".to_string(),
            full_name: "Maria Barbosa dos Santos".to_string(),
            document_cpf: Some("165.973.668-40".to_string()),
            document_rg: None,
            phone: "+55 11 98877-6655".to_string(),
            email: None,
            birth_date: Some("1985-03-20".to_string()),
            gender: Some("female".to_string()),
            marital_status: None,
            profession: None,
            emergency_contact_name: None,
            emergency_contact_phone: None,
            address_street: None,
            address_number: None,
            address_complement: None,
            address_neighborhood: None,
            address_city: None,
            address_state: None,
            address_zip: None,
            insurance_plan: None,
            insurance_number: None,
            legal_guardians: vec![],
            legal_guardian_name: None,
            legal_guardian_cpf: None,
            has_signature_password: false,
            created_at: "2026-08-20T10:00:00Z".to_string(),
            updated_at: "2026-08-20T10:00:00Z".to_string(),
        },
        Patient {
            id: "patient:margarida".to_string(),
            clinic_id: "clinic:smile_plus".to_string(),
            full_name: "Margarida Nascimento da Silva".to_string(),
            document_cpf: Some("196.550.148-60".to_string()),
            document_rg: None,
            phone: "+55 11 97766-5544".to_string(),
            email: None,
            birth_date: Some("1978-09-12".to_string()),
            gender: Some("female".to_string()),
            marital_status: None,
            profession: None,
            emergency_contact_name: None,
            emergency_contact_phone: None,
            address_street: None,
            address_number: None,
            address_complement: None,
            address_neighborhood: None,
            address_city: None,
            address_state: None,
            address_zip: None,
            insurance_plan: None,
            insurance_number: None,
            legal_guardians: vec![],
            legal_guardian_name: None,
            legal_guardian_cpf: None,
            has_signature_password: false,
            created_at: "2026-08-20T11:00:00Z".to_string(),
            updated_at: "2026-08-20T11:00:00Z".to_string(),
        },
        Patient {
            id: "patient:ana_flavia".to_string(),
            clinic_id: "clinic:smile_plus".to_string(),
            full_name: "Ana Flavia Pereira Barros".to_string(),
            document_cpf: Some("245.890.123-55".to_string()),
            document_rg: Some("SP-45.678.901".to_string()),
            phone: "+55 11 95356 5054".to_string(),
            email: Some("ana.flavia@exemplo.com".to_string()),
            birth_date: Some("1998-04-12".to_string()),
            gender: Some("female".to_string()),
            marital_status: Some("single".to_string()),
            profession: Some("Advogada".to_string()),
            emergency_contact_name: Some("Marcos Barros (Irmão)".to_string()),
            emergency_contact_phone: Some("+55 11 98888-1122".to_string()),
            address_street: Some("Rua Bela Cintra".to_string()),
            address_number: Some("1200".to_string()),
            address_complement: Some("Apto 84".to_string()),
            address_neighborhood: Some("Consolação".to_string()),
            address_city: Some("São Paulo".to_string()),
            address_state: Some("SP".to_string()),
            address_zip: Some("01415-000".to_string()),
            insurance_plan: None,
            insurance_number: None,
            legal_guardians: vec![],
            legal_guardian_name: None,
            legal_guardian_cpf: None,
            has_signature_password: true,
            created_at: "2026-08-01T14:30:00Z".to_string(),
            updated_at: "2026-08-20T10:00:00Z".to_string(),
        },
        Patient {
            id: "patient:carlos_barbosa".to_string(),
            clinic_id: "clinic:smile_plus".to_string(),
            full_name: "Carlos Barbosa".to_string(),
            document_cpf: Some("334.556.778-90".to_string()),
            document_rg: None,
            phone: "+55 11 92221 0294".to_string(),
            email: Some("carlos.barbosa@exemplo.com".to_string()),
            birth_date: Some("1980-07-22".to_string()),
            gender: Some("male".to_string()),
            marital_status: Some("married".to_string()),
            profession: Some("Comerciante".to_string()),
            emergency_contact_name: None,
            emergency_contact_phone: None,
            address_street: Some("Rua Teodoro Sampaio".to_string()),
            address_number: Some("800".to_string()),
            address_complement: None,
            address_neighborhood: Some("Pinheiros".to_string()),
            address_city: Some("São Paulo".to_string()),
            address_state: Some("SP".to_string()),
            address_zip: Some("05406-000".to_string()),
            insurance_plan: None,
            insurance_number: None,
            legal_guardians: vec![],
            legal_guardian_name: None,
            legal_guardian_cpf: None,
            has_signature_password: false,
            created_at: "2026-08-05T09:15:00Z".to_string(),
            updated_at: "2026-08-05T09:15:00Z".to_string(),
        },
        Patient {
            id: "patient:carlos_dias".to_string(),
            clinic_id: "clinic:smile_plus".to_string(),
            full_name: "Carlos Dias Soares da Silva".to_string(),
            document_cpf: Some("692.372.203-91".to_string()),
            document_rg: None,
            phone: "+55 11 96724 0823".to_string(),
            email: Some("carlos.dias@exemplo.com".to_string()),
            birth_date: Some("1975-03-10".to_string()),
            gender: Some("male".to_string()),
            marital_status: Some("married".to_string()),
            profession: Some("Contador".to_string()),
            emergency_contact_name: None,
            emergency_contact_phone: None,
            address_street: Some("Av. Rebouças".to_string()),
            address_number: Some("2500".to_string()),
            address_complement: None,
            address_neighborhood: Some("Pinheiros".to_string()),
            address_city: Some("São Paulo".to_string()),
            address_state: Some("SP".to_string()),
            address_zip: Some("05401-300".to_string()),
            insurance_plan: Some("Amil Dental".to_string()),
            insurance_number: Some("9938201".to_string()),
            legal_guardians: vec![],
            legal_guardian_name: None,
            legal_guardian_cpf: None,
            has_signature_password: true,
            created_at: "2026-08-10T11:00:00Z".to_string(),
            updated_at: "2026-08-10T11:00:00Z".to_string(),
        },
        Patient {
            id: "patient:carlos_roberto".to_string(),
            clinic_id: "clinic:smile_plus".to_string(),
            full_name: "Carlos Roberto de Paula".to_string(),
            document_cpf: Some("033.898.598-02".to_string()),
            document_rg: None,
            phone: "+55 11 95774 4089".to_string(),
            email: Some("carlos.roberto@exemplo.com".to_string()),
            birth_date: Some("1960-09-15".to_string()),
            gender: Some("male".to_string()),
            marital_status: Some("married".to_string()),
            profession: Some("Aposentado".to_string()),
            emergency_contact_name: None,
            emergency_contact_phone: None,
            address_street: Some("Rua Pamplona".to_string()),
            address_number: Some("650".to_string()),
            address_complement: None,
            address_neighborhood: Some("Jardim Paulista".to_string()),
            address_city: Some("São Paulo".to_string()),
            address_state: Some("SP".to_string()),
            address_zip: Some("01405-000".to_string()),
            insurance_plan: Some("Bradesco Dental".to_string()),
            insurance_number: Some("11223344".to_string()),
            legal_guardians: vec![],
            legal_guardian_name: None,
            legal_guardian_cpf: None,
            has_signature_password: false,
            created_at: "2026-08-12T16:20:00Z".to_string(),
            updated_at: "2026-08-12T16:20:00Z".to_string(),
        },
        Patient {
            id: "patient:edson_souza".to_string(),
            clinic_id: "clinic:smile_plus".to_string(),
            full_name: "Edson dos Santos Souza".to_string(),
            document_cpf: Some("048.565.185-85".to_string()),
            document_rg: None,
            phone: "+55 11 95759 3915".to_string(),
            email: None,
            birth_date: Some("1982-12-05".to_string()),
            gender: Some("male".to_string()),
            marital_status: Some("single".to_string()),
            profession: None,
            emergency_contact_name: None,
            emergency_contact_phone: None,
            address_street: None,
            address_number: None,
            address_complement: None,
            address_neighborhood: None,
            address_city: None,
            address_state: None,
            address_zip: None,
            insurance_plan: None,
            insurance_number: None,
            legal_guardians: vec![],
            legal_guardian_name: None,
            legal_guardian_cpf: None,
            has_signature_password: false,
            created_at: "2026-08-14T08:30:00Z".to_string(),
            updated_at: "2026-08-14T08:30:00Z".to_string(),
        },
        Patient {
            id: "patient:eliana_conceicao".to_string(),
            clinic_id: "clinic:smile_plus".to_string(),
            full_name: "Eliana da Conceição".to_string(),
            document_cpf: Some("222.534.948-79".to_string()),
            document_rg: None,
            phone: "+55 11 96297 3091".to_string(),
            email: None,
            birth_date: Some("1981-06-20".to_string()),
            gender: Some("female".to_string()),
            marital_status: Some("married".to_string()),
            profession: None,
            emergency_contact_name: None,
            emergency_contact_phone: None,
            address_street: None,
            address_number: None,
            address_complement: None,
            address_neighborhood: None,
            address_city: None,
            address_state: None,
            address_zip: None,
            insurance_plan: None,
            insurance_number: None,
            legal_guardians: vec![],
            legal_guardian_name: None,
            legal_guardian_cpf: None,
            has_signature_password: false,
            created_at: "2026-08-15T14:10:00Z".to_string(),
            updated_at: "2026-08-15T14:10:00Z".to_string(),
        },
        Patient {
            id: "patient:elmadini_larbi".to_string(),
            clinic_id: "clinic:smile_plus".to_string(),
            full_name: "Elmadini Larbi".to_string(),
            document_cpf: None,
            document_rg: None,
            phone: "+55 11 98300 9591".to_string(),
            email: None,
            birth_date: Some("1983-01-15".to_string()),
            gender: Some("male".to_string()),
            marital_status: None,
            profession: None,
            emergency_contact_name: None,
            emergency_contact_phone: None,
            address_street: None,
            address_number: None,
            address_complement: None,
            address_neighborhood: None,
            address_city: None,
            address_state: None,
            address_zip: None,
            insurance_plan: None,
            insurance_number: None,
            legal_guardians: vec![],
            legal_guardian_name: None,
            legal_guardian_cpf: None,
            has_signature_password: false,
            created_at: "2026-08-16T10:45:00Z".to_string(),
            updated_at: "2026-08-16T10:45:00Z".to_string(),
        },
        Patient {
            id: "patient:fernanda_alves".to_string(),
            clinic_id: "clinic:smile_plus".to_string(),
            full_name: "Fernanda Alves Dos Santos".to_string(),
            document_cpf: Some("277.222.888-63".to_string()),
            document_rg: None,
            phone: "+55 11 99642 4551".to_string(),
            email: None,
            birth_date: Some("1981-10-30".to_string()),
            gender: Some("female".to_string()),
            marital_status: None,
            profession: None,
            emergency_contact_name: None,
            emergency_contact_phone: None,
            address_street: None,
            address_number: None,
            address_complement: None,
            address_neighborhood: None,
            address_city: None,
            address_state: None,
            address_zip: None,
            insurance_plan: None,
            insurance_number: None,
            legal_guardians: vec![],
            legal_guardian_name: None,
            legal_guardian_cpf: None,
            has_signature_password: false,
            created_at: "2026-08-18T15:00:00Z".to_string(),
            updated_at: "2026-08-18T15:00:00Z".to_string(),
        },
        Patient {
            id: "patient:gislene_aparecida".to_string(),
            clinic_id: "clinic:smile_plus".to_string(),
            full_name: "Gislene Aparecida de Oliveira".to_string(),
            document_cpf: None,
            document_rg: None,
            phone: "+55 11 99311 6301".to_string(),
            email: None,
            birth_date: None,
            gender: Some("female".to_string()),
            marital_status: None,
            profession: None,
            emergency_contact_name: None,
            emergency_contact_phone: None,
            address_street: None,
            address_number: None,
            address_complement: None,
            address_neighborhood: None,
            address_city: None,
            address_state: None,
            address_zip: None,
            insurance_plan: None,
            insurance_number: None,
            legal_guardians: vec![],
            legal_guardian_name: None,
            legal_guardian_cpf: None,
            has_signature_password: false,
            created_at: "2026-08-20T09:00:00Z".to_string(),
            updated_at: "2026-08-20T09:00:00Z".to_string(),
        },
        Patient {
            id: "patient:iracema_miranda".to_string(),
            clinic_id: "clinic:smile_plus".to_string(),
            full_name: "Iracema Miranda dos Santos".to_string(),
            document_cpf: None,
            document_rg: None,
            phone: "+55 13 99678 2692".to_string(),
            email: None,
            birth_date: None,
            gender: Some("female".to_string()),
            marital_status: None,
            profession: None,
            emergency_contact_name: None,
            emergency_contact_phone: None,
            address_street: None,
            address_number: None,
            address_complement: None,
            address_neighborhood: None,
            address_city: None,
            address_state: None,
            address_zip: None,
            insurance_plan: None,
            insurance_number: None,
            legal_guardians: vec![],
            legal_guardian_name: None,
            legal_guardian_cpf: None,
            has_signature_password: false,
            created_at: "2026-08-22T11:20:00Z".to_string(),
            updated_at: "2026-08-22T11:20:00Z".to_string(),
        },
        Patient {
            id: "patient:mariana_castro".to_string(),
            clinic_id: "clinic:smile_plus".to_string(),
            full_name: "Mariana Castro Fernandes".to_string(),
            document_cpf: Some("123.456.789-00".to_string()),
            document_rg: Some("MG-12.345.678".to_string()),
            phone: "(11) 98765-4321".to_string(),
            email: Some("mariana.castro@exemplo.com".to_string()),
            birth_date: Some("1994-05-18".to_string()),
            gender: Some("female".to_string()),
            marital_status: Some("single".to_string()),
            profession: Some("Arquiteta".to_string()),
            emergency_contact_name: Some("Carlos Fernandes (Pai)".to_string()),
            emergency_contact_phone: Some("(11) 98111-2233".to_string()),
            address_street: Some("Av. Paulista".to_string()),
            address_number: Some("1000".to_string()),
            address_complement: Some("Apto 42".to_string()),
            address_neighborhood: Some("Bela Vista".to_string()),
            address_city: Some("São Paulo".to_string()),
            address_state: Some("SP".to_string()),
            address_zip: Some("01310-100".to_string()),
            insurance_plan: Some("Unimed Odonto".to_string()),
            insurance_number: Some("88492019".to_string()),
            legal_guardians: vec![],
            legal_guardian_name: None,
            legal_guardian_cpf: None,
            has_signature_password: false,
            created_at: "2026-08-01T10:00:00Z".to_string(),
            updated_at: "2026-08-20T14:30:00Z".to_string(),
        },
        Patient {
            id: "patient:lucas_souza".to_string(),
            clinic_id: "clinic:smile_plus".to_string(),
            full_name: "Lucas Gabriel de Souza".to_string(),
            document_cpf: Some("987.654.321-99".to_string()),
            document_rg: None,
            phone: "(11) 97654-3210".to_string(),
            email: Some("lucas.souza@exemplo.com".to_string()),
            birth_date: Some("1988-11-25".to_string()),
            gender: Some("male".to_string()),
            marital_status: Some("married".to_string()),
            profession: Some("Engenheiro".to_string()),
            emergency_contact_name: None,
            emergency_contact_phone: None,
            address_street: Some("Rua Augusta".to_string()),
            address_number: Some("450".to_string()),
            address_complement: None,
            address_neighborhood: Some("Consolação".to_string()),
            address_city: Some("São Paulo".to_string()),
            address_state: Some("SP".to_string()),
            address_zip: Some("01305-000".to_string()),
            insurance_plan: None,
            insurance_number: None,
            legal_guardians: vec![],
            legal_guardian_name: None,
            legal_guardian_cpf: None,
            has_signature_password: false,
            created_at: "2026-08-05T09:15:00Z".to_string(),
            updated_at: "2026-08-18T16:20:00Z".to_string(),
        },
        Patient {
            id: "patient:beatriz_lima".to_string(),
            clinic_id: "clinic:smile_plus".to_string(),
            full_name: "Beatriz Helena Lima".to_string(),
            document_cpf: Some("456.789.123-44".to_string()),
            document_rg: Some("SP-34.567.890".to_string()),
            phone: "(11) 99123-4567".to_string(),
            email: Some("beatriz.lima@exemplo.com".to_string()),
            birth_date: Some("2000-02-10".to_string()),
            gender: Some("female".to_string()),
            marital_status: Some("single".to_string()),
            profession: Some("Designer".to_string()),
            emergency_contact_name: Some("Renata Lima (Mãe)".to_string()),
            emergency_contact_phone: Some("(11) 99888-7766".to_string()),
            address_street: Some("Rua Oscar Freire".to_string()),
            address_number: Some("200".to_string()),
            address_complement: Some("Apto 101".to_string()),
            address_neighborhood: Some("Cerqueira César".to_string()),
            address_city: Some("São Paulo".to_string()),
            address_state: Some("SP".to_string()),
            address_zip: Some("01426-000".to_string()),
            insurance_plan: Some("Amil Dental".to_string()),
            insurance_number: Some("55432190".to_string()),
            legal_guardians: vec![],
            legal_guardian_name: None,
            legal_guardian_cpf: None,
            has_signature_password: true,
            created_at: "2026-08-10T11:00:00Z".to_string(),
            updated_at: "2026-08-22T08:45:00Z".to_string(),
        },
    ];

    let anamneses = vec![
        PatientAnamnesis {
            id: Some("anamnesis:mariana".to_string()),
            patient_id: "patient:mariana_castro".to_string(),
            clinic_id: "clinic:smile_plus".to_string(),
            template_type: Some("adult_standard".to_string()),
            custom_responses: vec![
                AnamnesisResponseItem {
                    question_id: "q_anesthesia".to_string(),
                    category: "Geral".to_string(),
                    question_text: "Já teve reação alérgica a anestesia local?".to_string(),
                    question_type: "yes_no".to_string(),
                    answer_boolean: Some(false),
                    answer_text: None,
                    notes: None,
                },
                AnamnesisResponseItem {
                    question_id: "q_hypertension".to_string(),
                    category: "Geral".to_string(),
                    question_text: "Possui histórico de hipertensão arterial?".to_string(),
                    question_type: "yes_no".to_string(),
                    answer_boolean: Some(false),
                    answer_text: None,
                    notes: None,
                },
            ],
            allergies: vec!["Dipirona".to_string()],
            continuous_medications: Some("Anticoncepcional".to_string()),
            systemic_diseases: vec![],
            is_pregnant: false,
            has_bleeding_disorder: false,
            smoker: false,
            bruxism: true,
            chief_complaint: Some("Sensibilidade no dente 21 ao tomar água gelada".to_string()),
            clinical_notes: Some("Paciente comunicativa e cooperativa.".to_string()),
            updated_at: "2026-08-01T10:30:00Z".to_string(),
            signature_status: Some("signed".to_string()),
            signing_token: None,
            signed_at: Some("2026-08-01T10:35:00Z".to_string()),
            signed_pdf_url: None,
        }
    ];

    let appointments = vec![
        AppointmentResponse {
            id: "app:ana_flavia_1".to_string(),
            clinic_id: "clinic:smile_plus".to_string(),
            patient_id: Some("patient:ana_flavia".to_string()),
            patient_name: Some("Ana Flavia Pereira Barros".to_string()),
            treatment_id: None,
            treatment_plan_id: None,
            title: "Avaliação & Profilaxia".to_string(),
            scheduled_for: "2026-08-28T18:00:00Z".to_string(),
            duration_minutes: 30,
            status: AppointmentStatus::Confirmed,
            appointment_type: AppointmentType::Consultation,
            financial_amount_cents: Some(15000),
            financial_type: Some("particular".to_string()),
            notes: Some("Primeira consulta de rotina.".to_string()),
            cancellation_reason: None,
            assigned_users: vec![
                AssignedUserDto {
                    user_id: "usr:dr_lucas".to_string(),
                    user_name: Some("Dr. Lucas Mendes".to_string()),
                    role_in_appointment: "Dentista Responsável".to_string(),
                    split_percentage: 100,
                },
            ],
            consumed_items: vec![],
            assigned_equipment: vec![],
        },
        AppointmentResponse {
            id: "app:1".to_string(),
            clinic_id: "clinic:smile_plus".to_string(),
            patient_id: Some("patient:mariana_castro".to_string()),
            patient_name: Some("Mariana Castro Fernandes".to_string()),
            treatment_id: None,
            treatment_plan_id: None,
            title: "Restauração Estética Resina".to_string(),
            scheduled_for: "2026-08-24T14:00:00Z".to_string(),
            duration_minutes: 30,
            status: AppointmentStatus::Confirmed,
            appointment_type: AppointmentType::Treatment,
            financial_amount_cents: Some(18000),
            financial_type: Some("particular".to_string()),
            notes: Some("Dente 21 - Faces V, M".to_string()),
            cancellation_reason: None,
            assigned_users: vec![
                AssignedUserDto {
                    user_id: "user:dr_lucas".to_string(),
                    user_name: Some("Dr. Lucas Mendes".to_string()),
                    role_in_appointment: "Cirurgião Dentista".to_string(),
                    split_percentage: 50,
                }
            ],
            consumed_items: vec![
                ConsumedItemDto {
                    item_id: "item:resina_z350".to_string(),
                    item_name: Some("Resina Filtek Z350 XT A2".to_string()),
                    quantity_planned: 1,
                    quantity_used: None,
                }
            ],
            assigned_equipment: vec![],
        },
        AppointmentResponse {
            id: "app:2".to_string(),
            clinic_id: "clinic:smile_plus".to_string(),
            patient_id: Some("patient:lucas_souza".to_string()),
            patient_name: Some("Lucas Gabriel de Souza".to_string()),
            treatment_id: None,
            treatment_plan_id: None,
            title: "Extração de Siso 38".to_string(),
            scheduled_for: "2026-08-25T15:30:00Z".to_string(),
            duration_minutes: 60,
            status: AppointmentStatus::Confirmed,
            appointment_type: AppointmentType::Surgery,
            financial_amount_cents: Some(45000),
            financial_type: Some("particular".to_string()),
            notes: Some("Kit cirúrgico preparado".to_string()),
            cancellation_reason: None,
            assigned_users: vec![
                AssignedUserDto {
                    user_id: "user:dr_lucas".to_string(),
                    user_name: Some("Dr. Lucas Mendes".to_string()),
                    role_in_appointment: "Cirurgião Dentista".to_string(),
                    split_percentage: 50,
                }
            ],
            consumed_items: vec![
                ConsumedItemDto {
                    item_id: "item:anestesico_artica".to_string(),
                    item_name: Some("Articaína 4% com Epinefrina 1:100.000".to_string()),
                    quantity_planned: 2,
                    quantity_used: None,
                }
            ],
            assigned_equipment: vec![],
        },
    ];

    let transactions = vec![
        Transaction {
            id: "tx:maria_barbosa_1".to_string(),
            clinic_id: "clinic:smile_plus".to_string(),
            appointment_id: None,
            patient_id: Some("patient:maria_barbosa".to_string()),
            patient_name: Some("Maria Barbosa dos Santos".to_string()),
            user_id: Some("usr:dr_lucas".to_string()),
            user_name: Some("Dr. Lucas Mendes".to_string()),
            treatment_plan_id: None,
            direction: TransactionDirection::Income,
            amount_cents: 25000,
            paid_amount_cents: 0,
            remaining_amount_cents: 25000,
            description: "Maria Barbosa dos Santos".to_string(),
            category: "Tratamento Odontológico".to_string(),
            due_date: "2026-08-25T10:00:00Z".to_string(),
            paid_date: None,
            payment_method: Some("pix".to_string()),
            status: TransactionStatus::Pending,
            installment_current: 1,
            installment_total: 1,
            is_calculated_pending: false,
            has_receipt: false,
            receipt_name: None,
            receipt_date: None,
            payments: vec![],
        },
        Transaction {
            id: "tx:maria_barbosa_2".to_string(),
            clinic_id: "clinic:smile_plus".to_string(),
            appointment_id: None,
            patient_id: Some("patient:maria_barbosa".to_string()),
            patient_name: Some("Maria Barbosa dos Santos".to_string()),
            user_id: Some("usr:dr_lucas".to_string()),
            user_name: Some("Dr. Lucas Mendes".to_string()),
            treatment_plan_id: None,
            direction: TransactionDirection::Income,
            amount_cents: 150000,
            paid_amount_cents: 0,
            remaining_amount_cents: 150000,
            description: "Maria Barbosa dos Santos".to_string(),
            category: "Prótese & Implante".to_string(),
            due_date: "2026-08-25T14:30:00Z".to_string(),
            paid_date: None,
            payment_method: Some("cartao_credito".to_string()),
            status: TransactionStatus::Pending,
            installment_current: 1,
            installment_total: 3,
            is_calculated_pending: false,
            has_receipt: false,
            receipt_name: None,
            receipt_date: None,
            payments: vec![],
        },
        Transaction {
            id: "tx:carlos_dias_1".to_string(),
            clinic_id: "clinic:smile_plus".to_string(),
            appointment_id: None,
            patient_id: Some("patient:carlos_dias".to_string()),
            patient_name: Some("Carlos Dias Soares da Silva".to_string()),
            user_id: Some("usr:dr_lucas".to_string()),
            user_name: Some("Dr. Lucas Mendes".to_string()),
            treatment_plan_id: None,
            direction: TransactionDirection::Income,
            amount_cents: 18000,
            paid_amount_cents: 18000,
            remaining_amount_cents: 0,
            description: "Carlos Dias Soares da Silva".to_string(),
            category: "Profilaxia & Raspagem".to_string(),
            due_date: "2026-08-24T11:00:00Z".to_string(),
            paid_date: Some("2026-08-24T11:00:00Z".to_string()),
            payment_method: Some("cartao_debito".to_string()),
            status: TransactionStatus::Paid,
            installment_current: 1,
            installment_total: 1,
            is_calculated_pending: false,
            has_receipt: true,
            receipt_name: Some("recibo_Carlos Dias Soares da Silva".to_string()),
            receipt_date: Some("24/08/2026".to_string()),
            payments: vec![
                TransactionPaymentEntry {
                    id: "pay:1".to_string(),
                    amount_cents: 18000,
                    paid_at: "2026-08-24T11:00:00Z".to_string(),
                    payment_method: "cartao_debito".to_string(),
                    notes: Some("Pagamento integral via Débito".to_string()),
                    registered_by_user_id: None,
                    registered_by_user_name: None,
                }
            ],
        },
        Transaction {
            id: "tx:margarida_1".to_string(),
            clinic_id: "clinic:smile_plus".to_string(),
            appointment_id: None,
            patient_id: Some("patient:margarida".to_string()),
            patient_name: Some("Margarida Nascimento da Silva".to_string()),
            user_id: Some("usr:dr_lucas".to_string()),
            user_name: Some("Dr. Lucas Mendes".to_string()),
            treatment_plan_id: None,
            direction: TransactionDirection::Income,
            amount_cents: 23000,
            paid_amount_cents: 0,
            remaining_amount_cents: 23000,
            description: "Margarida Nascimento da Silva".to_string(),
            category: "Restauração".to_string(),
            due_date: "2026-08-24T16:00:00Z".to_string(),
            paid_date: None,
            payment_method: Some("pix".to_string()),
            status: TransactionStatus::Pending,
            installment_current: 1,
            installment_total: 1,
            is_calculated_pending: false,
            has_receipt: false,
            receipt_name: None,
            receipt_date: None,
            payments: vec![],
        },
        Transaction {
            id: "tx:margarida_2".to_string(),
            clinic_id: "clinic:smile_plus".to_string(),
            appointment_id: None,
            patient_id: Some("patient:margarida".to_string()),
            patient_name: Some("Margarida Nascimento da Silva".to_string()),
            user_id: Some("usr:dr_lucas".to_string()),
            user_name: Some("Dr. Lucas Mendes".to_string()),
            treatment_plan_id: None,
            direction: TransactionDirection::Income,
            amount_cents: 180000,
            paid_amount_cents: 0,
            remaining_amount_cents: 180000,
            description: "Margarida Nascimento da Silva".to_string(),
            category: "Ortodontia".to_string(),
            due_date: "2026-08-24T16:30:00Z".to_string(),
            paid_date: None,
            payment_method: Some("boleto".to_string()),
            status: TransactionStatus::Pending,
            installment_current: 1,
            installment_total: 6,
            is_calculated_pending: false,
            has_receipt: false,
            receipt_name: None,
            receipt_date: None,
            payments: vec![],
        },
        Transaction {
            id: "tx:carlos_dias_2".to_string(),
            clinic_id: "clinic:smile_plus".to_string(),
            appointment_id: None,
            patient_id: Some("patient:carlos_dias".to_string()),
            patient_name: Some("Carlos Dias Soares da Silva".to_string()),
            user_id: Some("usr:dr_lucas".to_string()),
            user_name: Some("Dr. Lucas Mendes".to_string()),
            treatment_plan_id: None,
            direction: TransactionDirection::Income,
            amount_cents: 23000,
            paid_amount_cents: 23000,
            remaining_amount_cents: 0,
            description: "Carlos Dias Soares da Silva".to_string(),
            category: "Restauração".to_string(),
            due_date: "2026-08-22T09:30:00Z".to_string(),
            paid_date: Some("2026-08-22T09:30:00Z".to_string()),
            payment_method: Some("cartao_debito".to_string()),
            status: TransactionStatus::Paid,
            installment_current: 1,
            installment_total: 1,
            is_calculated_pending: false,
            has_receipt: true,
            receipt_name: Some("recibo_Carlos Dias Soares da Silva".to_string()),
            receipt_date: Some("22/08/2026".to_string()),
            payments: vec![
                TransactionPaymentEntry {
                    id: "pay:2".to_string(),
                    amount_cents: 23000,
                    paid_at: "2026-08-22T09:30:00Z".to_string(),
                    payment_method: "cartao_debito".to_string(),
                    notes: Some("Pago no cartão de débito".to_string()),
                    registered_by_user_id: None,
                    registered_by_user_name: None,
                }
            ],
        },
        Transaction {
            id: "tx:1".to_string(),
            clinic_id: "clinic:smile_plus".to_string(),
            appointment_id: Some("app:1".to_string()),
            patient_id: Some("patient:mariana_castro".to_string()),
            patient_name: Some("Mariana Castro Fernandes".to_string()),
            user_id: Some("user:dr_lucas".to_string()),
            user_name: Some("Dr. Lucas Mendes".to_string()),
            treatment_plan_id: None,
            direction: TransactionDirection::Income,
            amount_cents: 18000,
            paid_amount_cents: 18000,
            remaining_amount_cents: 0,
            description: "Restauração Dente 21 - Mariana Castro".to_string(),
            category: "Procedimentos Clínicos".to_string(),
            status: TransactionStatus::Paid,
            due_date: "2026-08-24T14:30:00Z".to_string(),
            paid_date: Some("2026-08-24T14:30:00Z".to_string()),
            payment_method: Some("Cartão de Crédito".to_string()),
            payments: vec![
                TransactionPaymentEntry {
                    id: "pay:1".to_string(),
                    paid_at: "2026-08-24T14:30:00Z".to_string(),
                    amount_cents: 18000,
                    payment_method: "Cartão de Crédito".to_string(),
                    notes: Some("Parcela única via Maquininha".to_string()),
                    registered_by_user_id: Some("user:admin_principal".to_string()),
                    registered_by_user_name: Some("Recepção".to_string()),
                }
            ],
            installment_current: 1,
            installment_total: 1,
            is_calculated_pending: false,
            has_receipt: false,
            receipt_name: None,
            receipt_date: None,
        },
        Transaction {
            id: "tx:2".to_string(),
            clinic_id: "clinic:smile_plus".to_string(),
            appointment_id: None,
            patient_id: None,
            patient_name: None,
            user_id: None,
            user_name: None,
            treatment_plan_id: None,
            direction: TransactionDirection::Expense,
            amount_cents: 35000,
            paid_amount_cents: 35000,
            remaining_amount_cents: 0,
            description: "Aquisição de Anestésicos e Resinas (Dental Cremer)".to_string(),
            category: "Suprimentos e Estoque".to_string(),
            status: TransactionStatus::Paid,
            due_date: "2026-08-20T10:00:00Z".to_string(),
            paid_date: Some("2026-08-20T10:00:00Z".to_string()),
            payment_method: Some("PIX".to_string()),
            payments: vec![],
            installment_current: 1,
            installment_total: 1,
            is_calculated_pending: false,
            has_receipt: false,
            receipt_name: None,
            receipt_date: None,
        },
    ];

    let inventory_items = vec![
        InventoryItem {
            id: "item:resina_z350".to_string(),
            clinic_id: "clinic:smile_plus".to_string(),
            item_type: ItemType::Material,
            name: "Resina Filtek Z350 XT A2 (4g)".to_string(),
            unit_type: "un".to_string(),
            current_stock: 14,
            min_stock: 5,
            cost_price_cents: 14500,
            manufacturer: Some("3M".to_string()),
            attachments: vec![],
            expiration_date: Some("2027-12-31".to_string()),
            batch_number: Some("L202408".to_string()),
            serial_number: None,
            warranty_until: None,
            next_maintenance_date: None,
            equipment_status: None,
            created_at: "2026-08-01T08:00:00Z".to_string(),
            updated_at: Some("2026-08-20T15:00:00Z".to_string()),
        },
        InventoryItem {
            id: "item:anestesico_artica".to_string(),
            clinic_id: "clinic:smile_plus".to_string(),
            item_type: ItemType::Chemical,
            name: "Articaína 4% c/ Epinefrina (50 tubetes)".to_string(),
            unit_type: "cx".to_string(),
            current_stock: 3,
            min_stock: 4,
            cost_price_cents: 21000,
            manufacturer: Some("DFL".to_string()),
            attachments: vec![],
            expiration_date: Some("2026-11-30".to_string()),
            batch_number: Some("ART2601".to_string()),
            serial_number: None,
            warranty_until: None,
            next_maintenance_date: None,
            equipment_status: None,
            created_at: "2026-08-01T08:00:00Z".to_string(),
            updated_at: Some("2026-08-22T10:00:00Z".to_string()),
        },
    ];

    let treatment_templates = vec![
        TreatmentTemplate {
            id: "tpl:consulta_inicial".to_string(),
            clinic_id: "clinic:smile_plus".to_string(),
            name: "Consulta Inicial & Avaliação".to_string(),
            category: Some("Diagnóstico".to_string()),
            description: Some("Exame clínico detalhado, anamnese e plano de tratamento.".to_string()),
            default_price_cents: 15000,
            estimated_duration_minutes: Some(30),
            dental_regions: vec!["Geral".to_string()],
            target_teeth: vec![],
            required_materials: vec![],
            required_equipment: vec![],
            post_care_instructions: None,
            clinical_notes: None,
            is_active: true,
            created_at: "2026-08-01T10:00:00Z".to_string(),
            updated_at: "2026-08-01T10:00:00Z".to_string(),
        },
        TreatmentTemplate {
            id: "tpl:restauracao_resina".to_string(),
            clinic_id: "clinic:smile_plus".to_string(),
            name: "Restauração em Resina Composta".to_string(),
            category: Some("Dentística".to_string()),
            description: Some("Remoção de cárie ou troca de restauração com resina fotopolimerizável.".to_string()),
            default_price_cents: 18000,
            estimated_duration_minutes: Some(45),
            dental_regions: vec!["Dente Específico".to_string()],
            target_teeth: vec![],
            required_materials: vec!["item:resina_z350".to_string()],
            required_equipment: vec![],
            post_care_instructions: Some("Evitar alimentos muito duros ou pigmentados nas primeiras 24 horas.".to_string()),
            clinical_notes: None,
            is_active: true,
            created_at: "2026-08-01T10:00:00Z".to_string(),
            updated_at: "2026-08-01T10:00:00Z".to_string(),
        },
        TreatmentTemplate {
            id: "tpl:profilaxia_ultrassom".to_string(),
            clinic_id: "clinic:smile_plus".to_string(),
            name: "Profilaxia & Raspagem Supragengival".to_string(),
            category: Some("Periodontia".to_string()),
            description: Some("Limpeza profissional com ultrassom e jato de bicarbonato/polimento.".to_string()),
            default_price_cents: 22000,
            estimated_duration_minutes: Some(40),
            dental_regions: vec!["Arcada Completa".to_string()],
            target_teeth: vec![],
            required_materials: vec![],
            required_equipment: vec![],
            post_care_instructions: None,
            clinical_notes: None,
            is_active: true,
            created_at: "2026-08-01T10:00:00Z".to_string(),
            updated_at: "2026-08-01T10:00:00Z".to_string(),
        },
    ];

    let users = vec![
        UserResponse {
            id: "user:admin_principal".to_string(),
            username: "admin".to_string(),
            full_name: "Dr. Roberto Alencar".to_string(),
            email: Some("roberto.alencar@smileplus.com".to_string()),
            phone: Some("(11) 98888-0001".to_string()),
            document_cpf: "111.222.333-44".to_string(),
            professional_registry: Some("CRO-SP 84920".to_string()),
            is_active: true,
            role: "admin".to_string(),
            permissions: vec![
                "patients:read".into(),
                "patients:write".into(),
                "agenda:read".into(),
                "agenda:write".into(),
                "finance:read".into(),
                "finance:write".into(),
                "stock:read".into(),
                "stock:write".into(),
                "treatments:read".into(),
                "treatments:write".into(),
                "settings:read".into(),
                "settings:write".into(),
            ],
            clinic_ids: vec!["clinic:smile_plus".to_string(), "clinic:luria_dent".to_string()],
        },
        UserResponse {
            id: "user:dr_lucas".to_string(),
            username: "dr.lucas".to_string(),
            full_name: "Dr. Lucas Mendes".to_string(),
            email: Some("lucas.mendes@smileplus.com".to_string()),
            phone: Some("(11) 97777-0002".to_string()),
            document_cpf: "222.333.444-55".to_string(),
            professional_registry: Some("CRO-SP 99120".to_string()),
            is_active: true,
            role: "dentist".to_string(),
            permissions: vec![
                "patients:read".into(),
                "patients:write".into(),
                "agenda:read".into(),
                "agenda:write".into(),
                "treatments:read".into(),
                "treatments:write".into(),
            ],
            clinic_ids: vec!["clinic:smile_plus".to_string()],
        },
        UserResponse {
            id: "user:recepcao".to_string(),
            username: "recepcao".to_string(),
            full_name: "Fernanda Oliveira".to_string(),
            email: Some("fernanda.oliveira@smileplus.com".to_string()),
            phone: Some("(11) 96666-0003".to_string()),
            document_cpf: "333.444.555-66".to_string(),
            professional_registry: None,
            is_active: true,
            role: "receptionist".to_string(),
            permissions: vec![
                "patients:read".into(),
                "patients:write".into(),
                "agenda:read".into(),
                "agenda:write".into(),
            ],
            clinic_ids: vec!["clinic:smile_plus".to_string()],
        },
    ];

    // Mapa de senhas mock (username -> senha em texto plano)
    // Credenciais: admin/Admin@123, dr.lucas/Lucas@456, recepcao/Recepcao@789
    let mut password_map = std::collections::HashMap::new();
    password_map.insert("admin".to_string(), "Admin@123".to_string());
    password_map.insert("dr.lucas".to_string(), "Lucas@456".to_string());
    password_map.insert("recepcao".to_string(), "Recepcao@789".to_string());

    let clinics = vec![
        ClinicResponse {
            id: "clinic:smile_plus".to_string(),
            corporate_name: "Smile Plus Odontologia Avançada Ltda".to_string(),
            trading_name: "Smile Plus - Matriz".to_string(),
            document_cnpj: "12.345.678/0001-90".to_string(),
            theme_color: "#0284c7".to_string(),
            logo_url: None,
            whatsapp_instance: Some("instance_smile_01".to_string()),
            address: ClinicAddress {
                street: "Av. Paulista".to_string(),
                number: "1000".to_string(),
                complement: Some("Conjunto 1401".to_string()),
                neighborhood: "Bela Vista".to_string(),
                city: "São Paulo".to_string(),
                state: "SP".to_string(),
                zip_code: "01310-100".to_string(),
            },
            auto_reminders: true,
            require_esign: true,
            smtp_host: None,
            smtp_port: None,
            smtp_user: None,
            smtp_from: None,
            smtp_tls: None,
            opening_hour: 8,
            closing_hour: 19,
        },
        ClinicResponse {
            id: "clinic:luria_dent".to_string(),
            corporate_name: "Luria Odontologia Integrada Ltda".to_string(),
            trading_name: "Luria Odontologia Integrada".to_string(),
            document_cnpj: "98.765.432/0001-10".to_string(),
            theme_color: "#0d9488".to_string(),
            logo_url: None,
            whatsapp_instance: None,
            address: ClinicAddress {
                street: "Rua Bela Cintra".to_string(),
                number: "500".to_string(),
                complement: None,
                neighborhood: "Consolação".to_string(),
                city: "São Paulo".to_string(),
                state: "SP".to_string(),
                zip_code: "01415-000".to_string(),
            },
            auto_reminders: true,
            require_esign: false,
            smtp_host: None,
            smtp_port: None,
            smtp_user: None,
            smtp_from: None,
            smtp_tls: None,
            opening_hour: 9,
            closing_hour: 18,
        }
    ];

    MockDatabase {
        patients,
        anamneses,
        exams: vec![],
        patient_treatments: vec![],
        appointments,
        transactions,
        inventory_items,
        stock_movements: vec![],
        treatment_templates,
        treatment_plans: vec![],
        contract_templates: vec![
            ContractTemplate {
                id: "tpl:contrato_servicos".to_string(),
                clinic_id: "clinic:smile_plus".to_string(),
                title: "Contrato de Prestação de Serviços Odontológicos".to_string(),
                category: "Jurídico / Contratos".to_string(),
                description: Some("Contrato padrão com cláusulas financeiras, garantias e obrigações.".to_string()),
                pdf_url: "/docs/contrato.pdf".to_string(),
                signature_fields: vec![],
                requires_patient_signature: true,
                requires_doctor_signature: true,
                allow_any_dentist_signature: true,
                created_at: "2026-08-20T10:00:00Z".to_string(),
                updated_at: "2026-08-20T10:00:00Z".to_string(),
            },
            ContractTemplate {
                id: "tpl:tcle".to_string(),
                clinic_id: "clinic:smile_plus".to_string(),
                title: "Termo de Consentimento Livre e Esclarecido (TCLE)".to_string(),
                category: "Termos & Autorizações".to_string(),
                description: Some("Esclarecimento de riscos, benefícios e alternativas do procedimento.".to_string()),
                pdf_url: "/docs/tcle.pdf".to_string(),
                signature_fields: vec![],
                requires_patient_signature: true,
                requires_doctor_signature: false,
                allow_any_dentist_signature: true,
                created_at: "2026-08-20T10:00:00Z".to_string(),
                updated_at: "2026-08-20T10:00:00Z".to_string(),
            },
            ContractTemplate {
                id: "tpl:atestado".to_string(),
                clinic_id: "clinic:smile_plus".to_string(),
                title: "Atestado Odontológico de Repouso".to_string(),
                category: "Atestados & Declarações".to_string(),
                description: Some("Atestado com CID e período de afastamento justificado.".to_string()),
                pdf_url: "/docs/atestado.pdf".to_string(),
                signature_fields: vec![],
                requires_patient_signature: false,
                requires_doctor_signature: true,
                allow_any_dentist_signature: true,
                created_at: "2026-08-20T10:00:00Z".to_string(),
                updated_at: "2026-08-20T10:00:00Z".to_string(),
            },
            ContractTemplate {
                id: "tpl:receituario".to_string(),
                clinic_id: "clinic:smile_plus".to_string(),
                title: "Receituário & Prescrição Medicamentosa".to_string(),
                category: "Receituários".to_string(),
                description: Some("Prescrição com posologia e orientações farmacológicas.".to_string()),
                pdf_url: "/docs/receituario.pdf".to_string(),
                signature_fields: vec![],
                requires_patient_signature: false,
                requires_doctor_signature: true,
                allow_any_dentist_signature: true,
                created_at: "2026-08-20T10:00:00Z".to_string(),
                updated_at: "2026-08-20T10:00:00Z".to_string(),
            },
        ],
        patient_documents: vec![
            PatientDocument {
                id: "doc:1".to_string(),
                clinic_id: "clinic:smile_plus".to_string(),
                patient_id: "patient:maria_barbosa".to_string(),
                patient_name: Some("Maria Barbosa dos Santos".to_string()),
                template_id: Some("tpl:contrato_servicos".to_string()),
                template_title: Some("Contrato de Prestação de Serviços Odontológicos".to_string()),
                doctor_user_id: Some("usr:dr_lucas".to_string()),
                doctor_user_name: Some("Dr. Lucas Mendes - CRO 12345".to_string()),
                appointment_id: None,
                title: "Contrato de Prestação de Serviços - Prótese".to_string(),
                document_type: "contract".to_string(),
                original_pdf_url: "/docs/contrato.pdf".to_string(),
                signed_pdf_url: None,
                status: "pending".to_string(),
                signing_token: "tok_maria_barbosa_123".to_string(),
                requires_patient_signature: true,
                requires_doctor_signature: true,
                allow_any_dentist_signature: true,
                patient_signed_at: None,
                patient_signature_data: None,
                doctor_signed_at: None,
                doctor_signature_data: None,
                patient_otp_verified: false,
                checksum_sha256: None,
                audit_trail: vec![],
                created_at: "2026-08-24T14:30:00Z".to_string(),
                updated_at: "2026-08-24T14:30:00Z".to_string(),
            },
            PatientDocument {
                id: "doc:2".to_string(),
                clinic_id: "clinic:smile_plus".to_string(),
                patient_id: "patient:carlos_dias".to_string(),
                patient_name: Some("Carlos Dias Soares da Silva".to_string()),
                template_id: Some("tpl:tcle".to_string()),
                template_title: Some("Termo de Consentimento Livre e Esclarecido (TCLE)".to_string()),
                doctor_user_id: Some("usr:dr_lucas".to_string()),
                doctor_user_name: Some("Dr. Lucas Mendes - CRO 12345".to_string()),
                appointment_id: None,
                title: "TCLE - Cirurgia de Terceiro Molar".to_string(),
                document_type: "consent".to_string(),
                original_pdf_url: "/docs/tcle.pdf".to_string(),
                signed_pdf_url: Some("/docs/tcle_assinado.pdf".to_string()),
                status: "signed".to_string(),
                signing_token: "tok_carlos_dias_456".to_string(),
                requires_patient_signature: true,
                requires_doctor_signature: false,
                allow_any_dentist_signature: true,
                patient_signed_at: Some("2026-08-22T09:35:00Z".to_string()),
                patient_signature_data: Some("data:image/png;base64,mock".to_string()),
                doctor_signed_at: None,
                doctor_signature_data: None,
                patient_otp_verified: true,
                checksum_sha256: Some("sha256_mock_hash_89712".to_string()),
                audit_trail: vec![],
                created_at: "2026-08-22T09:30:00Z".to_string(),
                updated_at: "2026-08-22T09:35:00Z".to_string(),
            },
        ],
        users,
        clinics,
        password_map,
    }
}
