//! # Banco de Dados em Memória para Desenvolvimento Mock-First
//!
//! Fornece armazenamento persistente em runtime WebAssembly para testes de UI
//! sem necessidade imediata do backend ativo.

use shared::anamnesis::AnamnesisResponseItem;
use shared::appointments::{
    AgendaResourceOption, AgendaResourcesResponse, AppointmentResponse,
    AppointmentStatus, AppointmentType, AssignedUserDto, ConsumedItemDto,
};
use shared::clinics::{ClinicAddress, ClinicResponse};
use shared::finance::{
    Transaction, TransactionDirection, TransactionPaymentEntry, TransactionStatus,
};
use shared::patients::{
    Patient, PatientAnamnesis, PatientExam, PatientTreatment,
};
use shared::stock::{
    EquipmentStatus, InventoryItem, ItemType, StockMovement,
};
use shared::treatments::{
    PatientTreatmentPlan, TreatmentTemplate,
};
use shared::users::UserResponse;
use std::sync::{LazyLock, Mutex};

pub struct MockDatabase {
    pub patients: Vec<Patient>,
    pub anamneses: Vec<PatientAnamnesis>,
    pub exams: Vec<PatientExam>,
    pub patient_treatments: Vec<PatientTreatment>,
    pub appointments: Vec<AppointmentResponse>,
    pub transactions: Vec<Transaction>,
    pub inventory_items: Vec<InventoryItem>,
    pub stock_movements: Vec<StockMovement>,
    pub treatment_templates: Vec<TreatmentTemplate>,
    pub treatment_plans: Vec<PatientTreatmentPlan>,
    pub users: Vec<UserResponse>,
    pub clinics: Vec<ClinicResponse>,
    /// Mapa username -> senha em texto plano (apenas para mock de desenvolvimento)
    pub password_map: std::collections::HashMap<String, String>,
}

pub static DB: LazyLock<Mutex<MockDatabase>> = LazyLock::new(|| Mutex::new(init_mock_database()));

fn init_mock_database() -> MockDatabase {
    let patients = vec![
        Patient {
            id: "patient:mariana_castro".to_string(),
            clinic_id: "clinic:smile_plus".to_string(),
            full_name: "Mariana Castro Fernandes".to_string(),
            document_cpf: Some("123.456.789-00".to_string()),
            document_rg: Some("MG-12.345.678".to_string()),
            phone: "(11) 98765-4321".to_string(),
            email: Some("mariana.castro@exemplo.com".to_string()),
            birth_date: Some("1994-05-18".to_string()),
            gender: Some("female".to_string()),
            marital_status: Some("single".to_string()),
            profession: Some("Arquiteta".to_string()),
            emergency_contact_name: Some("Carlos Fernandes (Pai)".to_string()),
            emergency_contact_phone: Some("(11) 98111-2233".to_string()),
            address_street: Some("Av. Paulista".to_string()),
            address_number: Some("1000".to_string()),
            address_complement: Some("Apto 42".to_string()),
            address_neighborhood: Some("Bela Vista".to_string()),
            address_city: Some("São Paulo".to_string()),
            address_state: Some("SP".to_string()),
            address_zip: Some("01310-100".to_string()),
            insurance_plan: Some("Unimed Odonto".to_string()),
            insurance_number: Some("88492019".to_string()),
            legal_guardians: vec![],
            legal_guardian_name: None,
            legal_guardian_cpf: None,
            has_signature_password: false,
            created_at: "2026-08-01T10:00:00Z".to_string(),
            updated_at: "2026-08-20T14:30:00Z".to_string(),
        },
        Patient {
            id: "patient:lucas_souza".to_string(),
            clinic_id: "clinic:smile_plus".to_string(),
            full_name: "Lucas Gabriel de Souza".to_string(),
            document_cpf: Some("987.654.321-99".to_string()),
            document_rg: None,
            phone: "(11) 97654-3210".to_string(),
            email: Some("lucas.souza@exemplo.com".to_string()),
            birth_date: Some("1988-11-25".to_string()),
            gender: Some("male".to_string()),
            marital_status: Some("married".to_string()),
            profession: Some("Engenheiro".to_string()),
            emergency_contact_name: None,
            emergency_contact_phone: None,
            address_street: Some("Rua Augusta".to_string()),
            address_number: Some("450".to_string()),
            address_complement: None,
            address_neighborhood: Some("Consolação".to_string()),
            address_city: Some("São Paulo".to_string()),
            address_state: Some("SP".to_string()),
            address_zip: Some("01305-000".to_string()),
            insurance_plan: None,
            insurance_number: None,
            legal_guardians: vec![],
            legal_guardian_name: None,
            legal_guardian_cpf: None,
            has_signature_password: false,
            created_at: "2026-08-05T09:15:00Z".to_string(),
            updated_at: "2026-08-18T16:20:00Z".to_string(),
        },
        Patient {
            id: "patient:beatriz_lima".to_string(),
            clinic_id: "clinic:smile_plus".to_string(),
            full_name: "Beatriz Helena Lima".to_string(),
            document_cpf: Some("456.789.123-44".to_string()),
            document_rg: Some("SP-34.567.890".to_string()),
            phone: "(11) 99123-4567".to_string(),
            email: Some("beatriz.lima@exemplo.com".to_string()),
            birth_date: Some("2000-02-10".to_string()),
            gender: Some("female".to_string()),
            marital_status: Some("single".to_string()),
            profession: Some("Designer".to_string()),
            emergency_contact_name: Some("Renata Lima (Mãe)".to_string()),
            emergency_contact_phone: Some("(11) 99888-7766".to_string()),
            address_street: Some("Rua Oscar Freire".to_string()),
            address_number: Some("200".to_string()),
            address_complement: Some("Apto 101".to_string()),
            address_neighborhood: Some("Cerqueira César".to_string()),
            address_city: Some("São Paulo".to_string()),
            address_state: Some("SP".to_string()),
            address_zip: Some("01426-000".to_string()),
            insurance_plan: Some("Amil Dental".to_string()),
            insurance_number: Some("55432190".to_string()),
            legal_guardians: vec![],
            legal_guardian_name: None,
            legal_guardian_cpf: None,
            has_signature_password: true,
            created_at: "2026-08-10T11:00:00Z".to_string(),
            updated_at: "2026-08-22T08:45:00Z".to_string(),
        },
    ];

    let anamneses = vec![
        PatientAnamnesis {
            id: Some("anamnesis:mariana".to_string()),
            patient_id: "patient:mariana_castro".to_string(),
            clinic_id: "clinic:smile_plus".to_string(),
            template_type: Some("adult_standard".to_string()),
            custom_responses: vec![
                AnamnesisResponseItem {
                    question_id: "q_anesthesia".to_string(),
                    category: "Geral".to_string(),
                    question_text: "Já teve reação alérgica a anestesia local?".to_string(),
                    question_type: "yes_no".to_string(),
                    answer_boolean: Some(false),
                    answer_text: None,
                    notes: None,
                },
                AnamnesisResponseItem {
                    question_id: "q_hypertension".to_string(),
                    category: "Geral".to_string(),
                    question_text: "Possui histórico de hipertensão arterial?".to_string(),
                    question_type: "yes_no".to_string(),
                    answer_boolean: Some(false),
                    answer_text: None,
                    notes: None,
                },
            ],
            allergies: vec!["Dipirona".to_string()],
            continuous_medications: Some("Anticoncepcional".to_string()),
            systemic_diseases: vec![],
            is_pregnant: false,
            has_bleeding_disorder: false,
            smoker: false,
            bruxism: true,
            chief_complaint: Some("Sensibilidade no dente 21 ao tomar água gelada".to_string()),
            clinical_notes: Some("Paciente comunicativa e cooperativa.".to_string()),
            updated_at: "2026-08-01T10:30:00Z".to_string(),
            signature_status: Some("signed".to_string()),
            signing_token: None,
            signed_at: Some("2026-08-01T10:35:00Z".to_string()),
            signed_pdf_url: None,
        }
    ];

    let appointments = vec![
        AppointmentResponse {
            id: "app:1".to_string(),
            clinic_id: "clinic:smile_plus".to_string(),
            patient_id: Some("patient:mariana_castro".to_string()),
            patient_name: Some("Mariana Castro Fernandes".to_string()),
            treatment_id: None,
            treatment_plan_id: None,
            title: "Restauração Estética Resina".to_string(),
            scheduled_for: "2026-08-24T14:00:00Z".to_string(),
            duration_minutes: 30,
            status: AppointmentStatus::Confirmed,
            appointment_type: AppointmentType::Treatment,
            financial_amount_cents: Some(18000),
            financial_type: Some("particular".to_string()),
            notes: Some("Dente 21 - Faces V, M".to_string()),
            cancellation_reason: None,
            assigned_users: vec![
                AssignedUserDto {
                    user_id: "user:dr_lucas".to_string(),
                    user_name: Some("Dr. Lucas Mendes".to_string()),
                    role_in_appointment: "Cirurgião Dentista".to_string(),
                    split_percentage: 50,
                }
            ],
            consumed_items: vec![
                ConsumedItemDto {
                    item_id: "item:resina_z350".to_string(),
                    item_name: Some("Resina Filtek Z350 XT A2".to_string()),
                    quantity_planned: 1,
                    quantity_used: None,
                }
            ],
            assigned_equipment: vec![],
        },
        AppointmentResponse {
            id: "app:2".to_string(),
            clinic_id: "clinic:smile_plus".to_string(),
            patient_id: Some("patient:lucas_souza".to_string()),
            patient_name: Some("Lucas Gabriel de Souza".to_string()),
            treatment_id: None,
            treatment_plan_id: None,
            title: "Extração de Siso 38".to_string(),
            scheduled_for: "2026-08-25T15:30:00Z".to_string(),
            duration_minutes: 60,
            status: AppointmentStatus::Confirmed,
            appointment_type: AppointmentType::Surgery,
            financial_amount_cents: Some(45000),
            financial_type: Some("particular".to_string()),
            notes: Some("Kit cirúrgico preparado".to_string()),
            cancellation_reason: None,
            assigned_users: vec![
                AssignedUserDto {
                    user_id: "user:dr_lucas".to_string(),
                    user_name: Some("Dr. Lucas Mendes".to_string()),
                    role_in_appointment: "Cirurgião Dentista".to_string(),
                    split_percentage: 50,
                }
            ],
            consumed_items: vec![
                ConsumedItemDto {
                    item_id: "item:anestesico_artica".to_string(),
                    item_name: Some("Articaína 4% com Epinefrina 1:100.000".to_string()),
                    quantity_planned: 2,
                    quantity_used: None,
                }
            ],
            assigned_equipment: vec![],
        },
    ];

    let transactions = vec![
        Transaction {
            id: "tx:1".to_string(),
            clinic_id: "clinic:smile_plus".to_string(),
            appointment_id: Some("app:1".to_string()),
            patient_id: Some("patient:mariana_castro".to_string()),
            patient_name: Some("Mariana Castro Fernandes".to_string()),
            user_id: Some("user:dr_lucas".to_string()),
            user_name: Some("Dr. Lucas Mendes".to_string()),
            treatment_plan_id: None,
            direction: TransactionDirection::Income,
            amount_cents: 18000,
            paid_amount_cents: 18000,
            remaining_amount_cents: 0,
            description: "Restauração Dente 21 - Mariana Castro".to_string(),
            category: "Procedimentos Clínicos".to_string(),
            status: TransactionStatus::Paid,
            due_date: "2026-08-24T14:30:00Z".to_string(),
            paid_date: Some("2026-08-24T14:30:00Z".to_string()),
            payment_method: Some("Cartão de Crédito".to_string()),
            payments: vec![
                TransactionPaymentEntry {
                    id: "pay:1".to_string(),
                    paid_at: "2026-08-24T14:30:00Z".to_string(),
                    amount_cents: 18000,
                    payment_method: "Cartão de Crédito".to_string(),
                    notes: Some("Parcela única via Maquininha".to_string()),
                    registered_by_user_id: Some("user:admin_principal".to_string()),
                    registered_by_user_name: Some("Recepção".to_string()),
                }
            ],
            installment_current: 1,
            installment_total: 1,
            is_calculated_pending: false,
        },
        Transaction {
            id: "tx:2".to_string(),
            clinic_id: "clinic:smile_plus".to_string(),
            appointment_id: None,
            patient_id: None,
            patient_name: None,
            user_id: None,
            user_name: None,
            treatment_plan_id: None,
            direction: TransactionDirection::Expense,
            amount_cents: 35000,
            paid_amount_cents: 35000,
            remaining_amount_cents: 0,
            description: "Aquisição de Anestésicos e Resinas (Dental Cremer)".to_string(),
            category: "Suprimentos e Estoque".to_string(),
            status: TransactionStatus::Paid,
            due_date: "2026-08-20T10:00:00Z".to_string(),
            paid_date: Some("2026-08-20T10:00:00Z".to_string()),
            payment_method: Some("PIX".to_string()),
            payments: vec![],
            installment_current: 1,
            installment_total: 1,
            is_calculated_pending: false,
        },
    ];

    let inventory_items = vec![
        InventoryItem {
            id: "item:resina_z350".to_string(),
            clinic_id: "clinic:smile_plus".to_string(),
            item_type: ItemType::Material,
            name: "Resina Filtek Z350 XT A2 (4g)".to_string(),
            unit_type: "un".to_string(),
            current_stock: 14,
            min_stock: 5,
            cost_price_cents: 14500,
            manufacturer: Some("3M".to_string()),
            attachments: vec![],
            expiration_date: Some("2027-12-31".to_string()),
            batch_number: Some("L202408".to_string()),
            serial_number: None,
            warranty_until: None,
            next_maintenance_date: None,
            equipment_status: None,
            created_at: "2026-08-01T08:00:00Z".to_string(),
            updated_at: Some("2026-08-20T15:00:00Z".to_string()),
        },
        InventoryItem {
            id: "item:anestesico_artica".to_string(),
            clinic_id: "clinic:smile_plus".to_string(),
            item_type: ItemType::Chemical,
            name: "Articaína 4% c/ Epinefrina (50 tubetes)".to_string(),
            unit_type: "cx".to_string(),
            current_stock: 3,
            min_stock: 4,
            cost_price_cents: 21000,
            manufacturer: Some("DFL".to_string()),
            attachments: vec![],
            expiration_date: Some("2026-11-30".to_string()),
            batch_number: Some("ART2601".to_string()),
            serial_number: None,
            warranty_until: None,
            next_maintenance_date: None,
            equipment_status: None,
            created_at: "2026-08-01T08:00:00Z".to_string(),
            updated_at: Some("2026-08-22T10:00:00Z".to_string()),
        },
    ];

    let treatment_templates = vec![
        TreatmentTemplate {
            id: "tpl:consulta_inicial".to_string(),
            clinic_id: "clinic:smile_plus".to_string(),
            name: "Consulta Inicial & Avaliação".to_string(),
            category: Some("Diagnóstico".to_string()),
            description: Some("Exame clínico detalhado, anamnese e plano de tratamento.".to_string()),
            default_price_cents: 15000,
            estimated_duration_minutes: Some(30),
            dental_regions: vec!["Geral".to_string()],
            target_teeth: vec![],
            required_materials: vec![],
            required_equipment: vec![],
            post_care_instructions: None,
            clinical_notes: None,
            is_active: true,
            created_at: "2026-08-01T10:00:00Z".to_string(),
            updated_at: "2026-08-01T10:00:00Z".to_string(),
        },
        TreatmentTemplate {
            id: "tpl:restauracao_resina".to_string(),
            clinic_id: "clinic:smile_plus".to_string(),
            name: "Restauração em Resina Composta".to_string(),
            category: Some("Dentística".to_string()),
            description: Some("Remoção de cárie ou troca de restauração com resina fotopolimerizável.".to_string()),
            default_price_cents: 18000,
            estimated_duration_minutes: Some(45),
            dental_regions: vec!["Dente Específico".to_string()],
            target_teeth: vec![],
            required_materials: vec!["item:resina_z350".to_string()],
            required_equipment: vec![],
            post_care_instructions: Some("Evitar alimentos muito duros ou pigmentados nas primeiras 24 horas.".to_string()),
            clinical_notes: None,
            is_active: true,
            created_at: "2026-08-01T10:00:00Z".to_string(),
            updated_at: "2026-08-01T10:00:00Z".to_string(),
        },
        TreatmentTemplate {
            id: "tpl:profilaxia_ultrassom".to_string(),
            clinic_id: "clinic:smile_plus".to_string(),
            name: "Profilaxia & Raspagem Supragengival".to_string(),
            category: Some("Periodontia".to_string()),
            description: Some("Limpeza profissional com ultrassom e jato de bicarbonato/polimento.".to_string()),
            default_price_cents: 22000,
            estimated_duration_minutes: Some(40),
            dental_regions: vec!["Arcada Completa".to_string()],
            target_teeth: vec![],
            required_materials: vec![],
            required_equipment: vec![],
            post_care_instructions: None,
            clinical_notes: None,
            is_active: true,
            created_at: "2026-08-01T10:00:00Z".to_string(),
            updated_at: "2026-08-01T10:00:00Z".to_string(),
        },
    ];

    let users = vec![
        UserResponse {
            id: "user:admin_principal".to_string(),
            username: "admin".to_string(),
            full_name: "Dr. Roberto Alencar".to_string(),
            email: Some("roberto.alencar@smileplus.com".to_string()),
            phone: Some("(11) 98888-0001".to_string()),
            document_cpf: "111.222.333-44".to_string(),
            professional_registry: Some("CRO-SP 84920".to_string()),
            is_active: true,
            role: "admin".to_string(),
            permissions: vec![
                "patients:read".into(),
                "patients:write".into(),
                "agenda:read".into(),
                "agenda:write".into(),
                "finance:read".into(),
                "finance:write".into(),
                "stock:read".into(),
                "stock:write".into(),
                "treatments:read".into(),
                "treatments:write".into(),
                "settings:read".into(),
                "settings:write".into(),
            ],
            clinic_ids: vec!["clinic:smile_plus".to_string(), "clinic:luria_dent".to_string()],
        },
        UserResponse {
            id: "user:dr_lucas".to_string(),
            username: "dr.lucas".to_string(),
            full_name: "Dr. Lucas Mendes".to_string(),
            email: Some("lucas.mendes@smileplus.com".to_string()),
            phone: Some("(11) 97777-0002".to_string()),
            document_cpf: "222.333.444-55".to_string(),
            professional_registry: Some("CRO-SP 99120".to_string()),
            is_active: true,
            role: "dentist".to_string(),
            permissions: vec![
                "patients:read".into(),
                "patients:write".into(),
                "agenda:read".into(),
                "agenda:write".into(),
                "treatments:read".into(),
                "treatments:write".into(),
            ],
            clinic_ids: vec!["clinic:smile_plus".to_string()],
        },
        UserResponse {
            id: "user:recepcao".to_string(),
            username: "recepcao".to_string(),
            full_name: "Fernanda Oliveira".to_string(),
            email: Some("fernanda.oliveira@smileplus.com".to_string()),
            phone: Some("(11) 96666-0003".to_string()),
            document_cpf: "333.444.555-66".to_string(),
            professional_registry: None,
            is_active: true,
            role: "receptionist".to_string(),
            permissions: vec![
                "patients:read".into(),
                "patients:write".into(),
                "agenda:read".into(),
                "agenda:write".into(),
            ],
            clinic_ids: vec!["clinic:smile_plus".to_string()],
        },
    ];

    // Mapa de senhas mock (username -> senha em texto plano)
    // Credenciais: admin/Admin@123, dr.lucas/Lucas@456, recepcao/Recepcao@789
    let mut password_map = std::collections::HashMap::new();
    password_map.insert("admin".to_string(), "Admin@123".to_string());
    password_map.insert("dr.lucas".to_string(), "Lucas@456".to_string());
    password_map.insert("recepcao".to_string(), "Recepcao@789".to_string());

    let clinics = vec![
        ClinicResponse {
            id: "clinic:smile_plus".to_string(),
            corporate_name: "Smile Plus Odontologia Avançada Ltda".to_string(),
            trading_name: "Smile Plus - Matriz".to_string(),
            document_cnpj: "12.345.678/0001-90".to_string(),
            theme_color: "#0284c7".to_string(),
            logo_url: None,
            whatsapp_instance: Some("instance_smile_01".to_string()),
            address: ClinicAddress {
                street: "Av. Paulista".to_string(),
                number: "1000".to_string(),
                complement: Some("Conjunto 1401".to_string()),
                neighborhood: "Bela Vista".to_string(),
                city: "São Paulo".to_string(),
                state: "SP".to_string(),
                zip_code: "01310-100".to_string(),
            },
            auto_reminders: true,
            require_esign: true,
            smtp_host: None,
            smtp_port: None,
            smtp_user: None,
            smtp_from: None,
            smtp_tls: None,
            opening_hour: 8,
            closing_hour: 19,
        },
        ClinicResponse {
            id: "clinic:luria_dent".to_string(),
            corporate_name: "Luria Odontologia Integrada Ltda".to_string(),
            trading_name: "Luria Odontologia Integrada".to_string(),
            document_cnpj: "98.765.432/0001-10".to_string(),
            theme_color: "#0d9488".to_string(),
            logo_url: None,
            whatsapp_instance: None,
            address: ClinicAddress {
                street: "Rua Bela Cintra".to_string(),
                number: "500".to_string(),
                complement: None,
                neighborhood: "Consolação".to_string(),
                city: "São Paulo".to_string(),
                state: "SP".to_string(),
                zip_code: "01415-000".to_string(),
            },
            auto_reminders: true,
            require_esign: false,
            smtp_host: None,
            smtp_port: None,
            smtp_user: None,
            smtp_from: None,
            smtp_tls: None,
            opening_hour: 9,
            closing_hour: 18,
        }
    ];

    MockDatabase {
        patients,
        anamneses,
        exams: vec![],
        patient_treatments: vec![],
        appointments,
        transactions,
        inventory_items,
        stock_movements: vec![],
        treatment_templates,
        treatment_plans: vec![],
        users,
        clinics,
        password_map,
    }
}
