pub mod patient_list_toolbar;
pub mod patient_list_table;
pub mod patient_profile_header;
pub mod tab_about;
pub mod tab_treatments;
pub mod tab_odontogram;
pub mod tab_debits;
pub mod tab_budgets;
pub mod tab_anamnesis;
pub mod tab_images;
pub mod tab_documents;

pub use patient_list_toolbar::PatientListToolbar;
pub use patient_list_table::PatientListTable;
pub use patient_profile_header::{PatientDetailTab, PatientProfileHeader};
pub use tab_about::TabAbout;
pub use tab_treatments::TabTreatments;
pub use tab_odontogram::TabOdontogram;
pub use tab_debits::TabDebits;
pub use tab_budgets::TabBudgets;
pub use tab_anamnesis::TabAnamnesis;
pub use tab_images::TabImages;
pub use tab_documents::TabDocuments;
